function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 22-Nov-2021 20:45:15

% Create figure
figure('WindowState','maximized','OuterPosition',[-7 33 1936 1056]);

% Create axes
axes1 = axes('Position',...
    [0.0379166666666667 0.0479750778816199 0.94053934769599 0.912564901349948]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Espectro modulado');

% Create ylabel
ylabel('Magnitud [dBm]');

% Create xlabel
xlabel('f [Hz]');

% Create title
title('Espectro Se\~{n}al');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[14846.0883621791 25307.38303729]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-55.5025125628141 -2.43718592964829]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend(axes1,'show');

